--------------------------------------------------------
--  파일이 생성됨 - 목요일-9월-03-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALERT_LOG
--------------------------------------------------------

  CREATE TABLE "SSA"."ALERT_LOG" 
   (	"ALERT_ID" NUMBER(*,0), 
	"ALERT_MSG" VARCHAR2(200 BYTE), 
	"SEND_STATUS" VARCHAR2(10 BYTE) DEFAULT '실패', 
	"SEND_DATE" DATE, 
	"DLOG_ID" NUMBER(*,0), 
	"FIRST_SEND_TIME" TIMESTAMP (6), 
	"ALERT_TYPE" VARCHAR2(10 BYTE), 
	"DANLOG_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."ALERT_LOG"."ALERT_ID" IS '경보이력시퀀스';
   COMMENT ON COLUMN "SSA"."ALERT_LOG"."ALERT_MSG" IS '경보알림메세지내용';
   COMMENT ON COLUMN "SSA"."ALERT_LOG"."SEND_STATUS" IS '전송성공여부';
   COMMENT ON COLUMN "SSA"."ALERT_LOG"."SEND_DATE" IS '경보전송일시';
   COMMENT ON COLUMN "SSA"."ALERT_LOG"."DLOG_ID" IS '탐지이력시퀀스';
   COMMENT ON COLUMN "SSA"."ALERT_LOG"."FIRST_SEND_TIME" IS '최초경보시각';
   COMMENT ON COLUMN "SSA"."ALERT_LOG"."ALERT_TYPE" IS '경보대상구분';
   COMMENT ON COLUMN "SSA"."ALERT_LOG"."DANLOG_ID" IS '이상객체탐지시퀀스';
   COMMENT ON TABLE "SSA"."ALERT_LOG"  IS '경보 이력';
--------------------------------------------------------
--  DDL for Table ANIMAL_COUNTER
--------------------------------------------------------

  CREATE TABLE "SSA"."ANIMAL_COUNTER" 
   (	"COUNTER_ID" NUMBER(*,0), 
	"CURRENT_COUNT" NUMBER(*,0) DEFAULT 0, 
	"LAST_UPDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."ANIMAL_COUNTER"."COUNTER_ID" IS '개채수시퀀스';
   COMMENT ON COLUMN "SSA"."ANIMAL_COUNTER"."CURRENT_COUNT" IS '현재보호개채수';
   COMMENT ON COLUMN "SSA"."ANIMAL_COUNTER"."LAST_UPDATE" IS '최종갱신일지';
   COMMENT ON TABLE "SSA"."ANIMAL_COUNTER"  IS '축종별 개채수 현황';
--------------------------------------------------------
--  DDL for Table ANIMAL_DETAIL
--------------------------------------------------------

  CREATE TABLE "SSA"."ANIMAL_DETAIL" 
   (	"ANIMAL_ID" NUMBER(*,0), 
	"ANIMAL_TYPE" VARCHAR2(10 BYTE), 
	"ANIMAL_BREED" VARCHAR2(50 BYTE), 
	"ANIMAL_NAME" VARCHAR2(50 BYTE), 
	"ENTRANCE_DATE" DATE DEFAULT SYSDATE, 
	"ANIMAL_STATUS" VARCHAR2(10 BYTE) DEFAULT '0'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."ANIMAL_DETAIL"."ANIMAL_ID" IS '동물식별시퀀스';
   COMMENT ON COLUMN "SSA"."ANIMAL_DETAIL"."ANIMAL_TYPE" IS '축종구분';
   COMMENT ON COLUMN "SSA"."ANIMAL_DETAIL"."ANIMAL_BREED" IS '품종구분';
   COMMENT ON COLUMN "SSA"."ANIMAL_DETAIL"."ANIMAL_NAME" IS '동물이름';
   COMMENT ON COLUMN "SSA"."ANIMAL_DETAIL"."ENTRANCE_DATE" IS '입소날자';
   COMMENT ON COLUMN "SSA"."ANIMAL_DETAIL"."ANIMAL_STATUS" IS '보호상태';
   COMMENT ON TABLE "SSA"."ANIMAL_DETAIL"  IS '동물 관리';
--------------------------------------------------------
--  DDL for Table COMMON_CODE
--------------------------------------------------------

  CREATE TABLE "SSA"."COMMON_CODE" 
   (	"GRP_CODE" VARCHAR2(20 BYTE), 
	"CODE" VARCHAR2(10 BYTE), 
	"CODE_NAME" VARCHAR2(50 BYTE), 
	"SORT_SEQ" NUMBER(*,0), 
	"USE_YN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CODE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."COMMON_CODE"."GRP_CODE" IS '그룹코드';
   COMMENT ON COLUMN "SSA"."COMMON_CODE"."CODE" IS '상세코드';
   COMMENT ON COLUMN "SSA"."COMMON_CODE"."CODE_NAME" IS '코드명칭';
   COMMENT ON COLUMN "SSA"."COMMON_CODE"."SORT_SEQ" IS '정렬순서';
   COMMENT ON COLUMN "SSA"."COMMON_CODE"."USE_YN" IS '사용여부';
   COMMENT ON COLUMN "SSA"."COMMON_CODE"."CODE_DATE" IS '코드등록일';
   COMMENT ON TABLE "SSA"."COMMON_CODE"  IS '시스템 공통관리';
--------------------------------------------------------
--  DDL for Table DANGER_DETAIL
--------------------------------------------------------

  CREATE TABLE "SSA"."DANGER_DETAIL" 
   (	"DANGER_ID" NUMBER(*,0), 
	"DANGER_NAME" VARCHAR2(50 BYTE), 
	"DANGER_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."DANGER_DETAIL"."DANGER_ID" IS '이상객체식별시퀀스';
   COMMENT ON COLUMN "SSA"."DANGER_DETAIL"."DANGER_NAME" IS '이상객체이름';
   COMMENT ON COLUMN "SSA"."DANGER_DETAIL"."DANGER_DATE" IS '등록일자';
   COMMENT ON TABLE "SSA"."DANGER_DETAIL"  IS '이상 객체 관리';
--------------------------------------------------------
--  DDL for Table DANGER_LOG
--------------------------------------------------------

  CREATE TABLE "SSA"."DANGER_LOG" 
   (	"DANLOG_ID" NUMBER(*,0), 
	"DANGER_TYPE" NUMBER(*,0), 
	"DANGER_TIME" TIMESTAMP (6), 
	"DACTION_STATUS" VARCHAR2(1 BYTE) DEFAULT '0', 
	"DACTION_REASON" VARCHAR2(4000 BYTE), 
	"DSNAPSHOT_PATH" VARCHAR2(255 BYTE), 
	"DANGER_DATE" DATE DEFAULT SYSDATE, 
	"DRONE_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."DANGER_LOG"."DANLOG_ID" IS '이상객체탐지시퀀스';
   COMMENT ON COLUMN "SSA"."DANGER_LOG"."DANGER_TYPE" IS '탐지된이상객체';
   COMMENT ON COLUMN "SSA"."DANGER_LOG"."DANGER_TIME" IS '탐지시각';
   COMMENT ON COLUMN "SSA"."DANGER_LOG"."DACTION_STATUS" IS '조치상태';
   COMMENT ON COLUMN "SSA"."DANGER_LOG"."DACTION_REASON" IS '현장조치사유';
   COMMENT ON COLUMN "SSA"."DANGER_LOG"."DSNAPSHOT_PATH" IS '포착스냅샷이미지';
   COMMENT ON COLUMN "SSA"."DANGER_LOG"."DANGER_DATE" IS '시스템로그적재일';
   COMMENT ON COLUMN "SSA"."DANGER_LOG"."DRONE_ID" IS '드론';
   COMMENT ON TABLE "SSA"."DANGER_LOG"  IS '이상 객체 탐지 이력';
--------------------------------------------------------
--  DDL for Table DETECTION_LOG
--------------------------------------------------------

  CREATE TABLE "SSA"."DETECTION_LOG" 
   (	"DLOG_ID" NUMBER(*,0), 
	"DETECT_TIME" TIMESTAMP (6), 
	"ANIMAL_TYPE" VARCHAR2(10 BYTE), 
	"SNAPSHOT_PATH" VARCHAR2(255 BYTE), 
	"DETECTION_DATE" DATE, 
	"DRONE_ID" VARCHAR2(30 BYTE), 
	"ACTION_STATUS" VARCHAR2(1 BYTE) DEFAULT '0', 
	"ACTION_REASON" VARCHAR2(4000 BYTE), 
	"DETECT_COUNT" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."DLOG_ID" IS '탐지이력시퀀스';
   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."DETECT_TIME" IS '탐지시각';
   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."ANIMAL_TYPE" IS '축종구분';
   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."SNAPSHOT_PATH" IS '포착스냅샷경로';
   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."DETECTION_DATE" IS '로그적재일시';
   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."DRONE_ID" IS '드론';
   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."ACTION_STATUS" IS '조치상태';
   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."ACTION_REASON" IS '현장조치사유';
   COMMENT ON COLUMN "SSA"."DETECTION_LOG"."DETECT_COUNT" IS '개체수';
   COMMENT ON TABLE "SSA"."DETECTION_LOG"  IS '탐지 이력';
--------------------------------------------------------
--  DDL for Table DRONE
--------------------------------------------------------

  CREATE TABLE "SSA"."DRONE" 
   (	"DRONE_ID" VARCHAR2(30 BYTE), 
	"MEMBER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."DRONE"."DRONE_ID" IS '드론';
   COMMENT ON COLUMN "SSA"."DRONE"."MEMBER_ID" IS '사번';
   COMMENT ON TABLE "SSA"."DRONE"  IS '드론';
--------------------------------------------------------
--  DDL for Table FLIGHT_HISTORY
--------------------------------------------------------

  CREATE TABLE "SSA"."FLIGHT_HISTORY" 
   (	"FLIGHT_ID" NUMBER(*,0), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"FLIGHT_DURATION" NUMBER(5,2), 
	"BATTERY_CONSUMPTION" NUMBER(5,2), 
	"FLIGHT_DATE" DATE, 
	"DRONE_ID" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."FLIGHT_HISTORY"."FLIGHT_ID" IS '비행이력시퀀스';
   COMMENT ON COLUMN "SSA"."FLIGHT_HISTORY"."START_TIME" IS '비행시작일시';
   COMMENT ON COLUMN "SSA"."FLIGHT_HISTORY"."END_TIME" IS '비행종료일시';
   COMMENT ON COLUMN "SSA"."FLIGHT_HISTORY"."FLIGHT_DURATION" IS '총비행시간';
   COMMENT ON COLUMN "SSA"."FLIGHT_HISTORY"."BATTERY_CONSUMPTION" IS '베터리소모량';
   COMMENT ON COLUMN "SSA"."FLIGHT_HISTORY"."FLIGHT_DATE" IS '데이터등록일시';
   COMMENT ON COLUMN "SSA"."FLIGHT_HISTORY"."DRONE_ID" IS '드론';
   COMMENT ON TABLE "SSA"."FLIGHT_HISTORY"  IS '비행 이력';
--------------------------------------------------------
--  DDL for Table HO_LOCK
--------------------------------------------------------

  CREATE TABLE "SSA"."HO_LOCK" 
   (	"LOCK_ID" NUMBER(*,0), 
	"LOCK_TYPE" VARCHAR2(50 BYTE), 
	"LOCK_TYPE_ID" NUMBER(*,0), 
	"HANDOVER_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."HO_LOCK"."LOCK_ID" IS '락킹시퀀스';
   COMMENT ON COLUMN "SSA"."HO_LOCK"."LOCK_TYPE" IS '락킹대상';
   COMMENT ON COLUMN "SSA"."HO_LOCK"."LOCK_TYPE_ID" IS '락킹도메인';
   COMMENT ON COLUMN "SSA"."HO_LOCK"."HANDOVER_ID" IS '인수인계시퀀스';
   COMMENT ON TABLE "SSA"."HO_LOCK"  IS '미결 사항 락킹';
--------------------------------------------------------
--  DDL for Table HO_NOTE
--------------------------------------------------------

  CREATE TABLE "SSA"."HO_NOTE" 
   (	"HANDOVER_ID" NUMBER(*,0), 
	"HANDOVER_STATUS" VARCHAR2(1 BYTE) DEFAULT '0', 
	"HANDOVER_CONTENT" VARCHAR2(4000 BYTE), 
	"HANDOVER_DATE" DATE, 
	"HANDOUT_SIGN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"HANDIN_SIGN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"HO_MEMBER_ID" VARCHAR2(50 BYTE), 
	"HI_MEMBER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."HO_NOTE"."HANDOVER_ID" IS '인수인계시퀀스';
   COMMENT ON COLUMN "SSA"."HO_NOTE"."HANDOVER_STATUS" IS '인수인계상태';
   COMMENT ON COLUMN "SSA"."HO_NOTE"."HANDOVER_CONTENT" IS '인수인계내용';
   COMMENT ON COLUMN "SSA"."HO_NOTE"."HANDOVER_DATE" IS '교대근무일자';
   COMMENT ON COLUMN "SSA"."HO_NOTE"."HANDOUT_SIGN" IS '인계자서명여부';
   COMMENT ON COLUMN "SSA"."HO_NOTE"."HANDIN_SIGN" IS '인수자서명여부';
   COMMENT ON COLUMN "SSA"."HO_NOTE"."HO_MEMBER_ID" IS '인계자사번';
   COMMENT ON COLUMN "SSA"."HO_NOTE"."HI_MEMBER_ID" IS '인수사사번';
   COMMENT ON TABLE "SSA"."HO_NOTE"  IS '인수인계 이력';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SSA"."MEMBER" 
   (	"MEMBER_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT '0', 
	"FAIL_COUNT" NUMBER(*,0) DEFAULT 0, 
	"PWD_CHG_DATE" DATE DEFAULT SYSDATE, 
	"LAST_LONG_DATE" DATE, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"PHONE" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(300 BYTE), 
	"PICTURE" VARCHAR2(200 BYTE) DEFAULT 'noImage.jpg'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."MEMBER"."MEMBER_ID" IS '사번';
   COMMENT ON COLUMN "SSA"."MEMBER"."NAME" IS '이름';
   COMMENT ON COLUMN "SSA"."MEMBER"."DEPARTMENT" IS '소속';
   COMMENT ON COLUMN "SSA"."MEMBER"."PASSWORD" IS '비밀번호';
   COMMENT ON COLUMN "SSA"."MEMBER"."STATUS" IS '계정상태';
   COMMENT ON COLUMN "SSA"."MEMBER"."FAIL_COUNT" IS '로그인실패횟수';
   COMMENT ON COLUMN "SSA"."MEMBER"."PWD_CHG_DATE" IS '마지막비밀번호변경일';
   COMMENT ON COLUMN "SSA"."MEMBER"."LAST_LONG_DATE" IS '마지막로그인일시';
   COMMENT ON COLUMN "SSA"."MEMBER"."REG_DATE" IS '계정등록일';
   COMMENT ON COLUMN "SSA"."MEMBER"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "SSA"."MEMBER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "SSA"."MEMBER"."PICTURE" IS '사진경로';
   COMMENT ON TABLE "SSA"."MEMBER"  IS '직원 계정';
--------------------------------------------------------
--  DDL for Table MEMBER_LOG
--------------------------------------------------------

  CREATE TABLE "SSA"."MEMBER_LOG" 
   (	"LOG_ID" NUMBER(*,0), 
	"LOGIN_IP" VARCHAR2(20 BYTE), 
	"LOGIN_STATUS" VARCHAR2(50 BYTE), 
	"LOGIN_DATE" DATE, 
	"MEMBER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."MEMBER_LOG"."LOG_ID" IS '로그인이력시퀀스';
   COMMENT ON COLUMN "SSA"."MEMBER_LOG"."LOGIN_IP" IS '요청IP주소';
   COMMENT ON COLUMN "SSA"."MEMBER_LOG"."LOGIN_STATUS" IS '로그인결과상태';
   COMMENT ON COLUMN "SSA"."MEMBER_LOG"."LOGIN_DATE" IS '로그인시도일시';
   COMMENT ON COLUMN "SSA"."MEMBER_LOG"."MEMBER_ID" IS '사번';
   COMMENT ON TABLE "SSA"."MEMBER_LOG"  IS '로그인 이력';
--------------------------------------------------------
--  DDL for Table MEMBER_ROLE
--------------------------------------------------------

  CREATE TABLE "SSA"."MEMBER_ROLE" 
   (	"ROLE_ID" NUMBER(*,0), 
	"ROLE_CODE" VARCHAR2(20 BYTE) DEFAULT 'ROLE_GUEST', 
	"MEMBER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."MEMBER_ROLE"."ROLE_ID" IS '권한번호';
   COMMENT ON COLUMN "SSA"."MEMBER_ROLE"."ROLE_CODE" IS '권한명칭';
   COMMENT ON COLUMN "SSA"."MEMBER_ROLE"."MEMBER_ID" IS '사번';
   COMMENT ON TABLE "SSA"."MEMBER_ROLE"  IS '권한 관리';
--------------------------------------------------------
--  DDL for Table PATROL_REPORT
--------------------------------------------------------

  CREATE TABLE "SSA"."PATROL_REPORT" 
   (	"REPORT_ID" NUMBER(*,0), 
	"REPORT_DATE" DATE, 
	"TOTAL_FLIGHT_TIME" NUMBER(5,2), 
	"TOTAL_DETECT_COUNT" NUMBER(*,0) DEFAULT 0, 
	"COMPLETION_RATE" NUMBER(5,2), 
	"CONFIRM_STATUS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PATROL_DATE" DATE, 
	"MOD_DATE" DATE, 
	"MEMBER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."REPORT_ID" IS '리포트시퀀스';
   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."REPORT_DATE" IS '리포트기준일자';
   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."TOTAL_FLIGHT_TIME" IS '당일드롱총비행시간';
   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."TOTAL_DETECT_COUNT" IS '당일탐지총건수';
   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."COMPLETION_RATE" IS '당일조치완료율';
   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."CONFIRM_STATUS" IS '관제원확정여부';
   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."PATROL_DATE" IS '최초집계일시';
   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."MOD_DATE" IS '수동강제재실행';
   COMMENT ON COLUMN "SSA"."PATROL_REPORT"."MEMBER_ID" IS '사번';
   COMMENT ON TABLE "SSA"."PATROL_REPORT"  IS '일일 리포트';
--------------------------------------------------------
--  DDL for Table PDF_CACHE
--------------------------------------------------------

  CREATE TABLE "SSA"."PDF_CACHE" 
   (	"PDF_CACHE_ID" NUMBER(*,0), 
	"PDF_FILE_PATH" VARCHAR2(255 BYTE), 
	"GENERATION_STATUS" VARCHAR2(10 BYTE) DEFAULT 'REQUEST', 
	"PDF_DATE" DATE, 
	"REPORT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."PDF_CACHE"."PDF_CACHE_ID" IS 'PDF캐시식별자시퀀스';
   COMMENT ON COLUMN "SSA"."PDF_CACHE"."PDF_FILE_PATH" IS 'PDF파일경로';
   COMMENT ON COLUMN "SSA"."PDF_CACHE"."GENERATION_STATUS" IS 'PDF생성상태';
   COMMENT ON COLUMN "SSA"."PDF_CACHE"."PDF_DATE" IS 'PDF캐싱일지';
   COMMENT ON COLUMN "SSA"."PDF_CACHE"."REPORT_ID" IS '리포트시퀀스';
   COMMENT ON TABLE "SSA"."PDF_CACHE"  IS 'PDF 캐싱 이력';
--------------------------------------------------------
--  DDL for Table WORKFLOW
--------------------------------------------------------

  CREATE TABLE "SSA"."WORKFLOW" 
   (	"APPROVAL_ID" NUMBER(*,0), 
	"APP_STATUS" VARCHAR2(1 BYTE) DEFAULT '0', 
	"REJECT_REASON" VARCHAR2(4000 BYTE), 
	"ADMIN_SIGN" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"REQUEST_DATE" DATE, 
	"COMPLETE_DATE" DATE DEFAULT SYSDATE, 
	"DRAFTER_ID" VARCHAR2(50 BYTE), 
	"APPROVER_ID" VARCHAR2(50 BYTE), 
	"REPORT_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SSA"."WORKFLOW"."APPROVAL_ID" IS '전자결재건시퀀스';
   COMMENT ON COLUMN "SSA"."WORKFLOW"."APP_STATUS" IS '결재상태';
   COMMENT ON COLUMN "SSA"."WORKFLOW"."REJECT_REASON" IS '반려사유내용';
   COMMENT ON COLUMN "SSA"."WORKFLOW"."ADMIN_SIGN" IS '관리자서명여부';
   COMMENT ON COLUMN "SSA"."WORKFLOW"."REQUEST_DATE" IS '최종상신기안일시';
   COMMENT ON COLUMN "SSA"."WORKFLOW"."COMPLETE_DATE" IS '최종승인반려완료';
   COMMENT ON COLUMN "SSA"."WORKFLOW"."DRAFTER_ID" IS '기안사사번';
   COMMENT ON COLUMN "SSA"."WORKFLOW"."APPROVER_ID" IS '관리자사번';
   COMMENT ON COLUMN "SSA"."WORKFLOW"."REPORT_ID" IS '리포트시퀀스';
   COMMENT ON TABLE "SSA"."WORKFLOW"  IS '결재 관리 이력';
REM INSERTING into SSA.ALERT_LOG
SET DEFINE OFF;
REM INSERTING into SSA.ANIMAL_COUNTER
SET DEFINE OFF;
Insert into SSA.ANIMAL_COUNTER (COUNTER_ID,CURRENT_COUNT,LAST_UPDATE) values (0,2,to_date('26/09/02','RR/MM/DD'));
Insert into SSA.ANIMAL_COUNTER (COUNTER_ID,CURRENT_COUNT,LAST_UPDATE) values (1,1,to_date('26/09/02','RR/MM/DD'));
REM INSERTING into SSA.ANIMAL_DETAIL
SET DEFINE OFF;
Insert into SSA.ANIMAL_DETAIL (ANIMAL_ID,ANIMAL_TYPE,ANIMAL_BREED,ANIMAL_NAME,ENTRANCE_DATE,ANIMAL_STATUS) values (1,'0','말티즈','루루',to_date('26/09/02','RR/MM/DD'),'0');
Insert into SSA.ANIMAL_DETAIL (ANIMAL_ID,ANIMAL_TYPE,ANIMAL_BREED,ANIMAL_NAME,ENTRANCE_DATE,ANIMAL_STATUS) values (2,'0','진돗개','라라',to_date('26/09/02','RR/MM/DD'),'0');
Insert into SSA.ANIMAL_DETAIL (ANIMAL_ID,ANIMAL_TYPE,ANIMAL_BREED,ANIMAL_NAME,ENTRANCE_DATE,ANIMAL_STATUS) values (3,'0','불독','단단',to_date('26/09/02','RR/MM/DD'),'0');
Insert into SSA.ANIMAL_DETAIL (ANIMAL_ID,ANIMAL_TYPE,ANIMAL_BREED,ANIMAL_NAME,ENTRANCE_DATE,ANIMAL_STATUS) values (4,'1','치즈','치치',to_date('26/09/02','RR/MM/DD'),'0');
Insert into SSA.ANIMAL_DETAIL (ANIMAL_ID,ANIMAL_TYPE,ANIMAL_BREED,ANIMAL_NAME,ENTRANCE_DATE,ANIMAL_STATUS) values (5,'1','렉돌','렉렉',to_date('26/09/02','RR/MM/DD'),'0');
REM INSERTING into SSA.COMMON_CODE
SET DEFINE OFF;
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ACCOUNT_STATUS','0','정상',1,'Y',to_date('26/09/01','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ACCOUNT_STATUS','1','정지',2,'Y',to_date('26/09/01','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ACCOUNT_STATUS','2','휴면',3,'Y',to_date('26/09/01','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('USER_ROLE','ROLE_ADMIN','관리자',1,'Y',to_date('26/09/01','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('USER_ROLE','ROLE_GUEST','미인가',3,'Y',to_date('26/09/01','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('USER_ROLE','ROLE_USER','관제원',2,'Y',to_date('26/09/01','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ANIMAL_TYPE','0','개',1,'Y',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ANIMAL_TYPE','1','고양이',2,'Y',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ACTION_STATUS','0','미확인',1,'Y',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ACTION_STATUS','1','포획',2,'Y',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ACTION_STATUS','2','인계',3,'Y',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ANIMAL_STATUS','0','보호중',1,'Y',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ANIMAL_STATUS','1','입양',2,'Y',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.COMMON_CODE (GRP_CODE,CODE,CODE_NAME,SORT_SEQ,USE_YN,CODE_DATE) values ('ANIMAL_STATUS','2','퇴소',3,'Y',to_date('26/09/02','RR/MM/DD'));
REM INSERTING into SSA.DANGER_DETAIL
SET DEFINE OFF;
Insert into SSA.DANGER_DETAIL (DANGER_ID,DANGER_NAME,DANGER_DATE) values (1,'용',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.DANGER_DETAIL (DANGER_ID,DANGER_NAME,DANGER_DATE) values (3,'외계인',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.DANGER_DETAIL (DANGER_ID,DANGER_NAME,DANGER_DATE) values (2,'용',to_date('26/09/02','RR/MM/DD'));
Insert into SSA.DANGER_DETAIL (DANGER_ID,DANGER_NAME,DANGER_DATE) values (4,'호랑이',to_date('26/09/02','RR/MM/DD'));
REM INSERTING into SSA.DANGER_LOG
SET DEFINE OFF;
Insert into SSA.DANGER_LOG (DANLOG_ID,DANGER_TYPE,DANGER_TIME,DACTION_STATUS,DACTION_REASON,DSNAPSHOT_PATH,DANGER_DATE,DRONE_ID) values (1,1,to_timestamp('26/09/02 13:03:20.965000000','RR/MM/DD HH24:MI:SSXFF'),'0','드론 야간 순찰 중 멧돼지 추정 객체 무리 식별','/resources/images/boar.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_01');
Insert into SSA.DANGER_LOG (DANLOG_ID,DANGER_TYPE,DANGER_TIME,DACTION_STATUS,DACTION_REASON,DSNAPSHOT_PATH,DANGER_DATE,DRONE_ID) values (2,2,to_timestamp('26/09/02 14:03:20.967000000','RR/MM/DD HH24:MI:SSXFF'),'1','산림 경계 구역 고라니 출몰로 현장 순찰 대기','/resources/images/deer.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_02');
Insert into SSA.DANGER_LOG (DANLOG_ID,DANGER_TYPE,DANGER_TIME,DACTION_STATUS,DACTION_REASON,DSNAPSHOT_PATH,DANGER_DATE,DRONE_ID) values (3,1,to_timestamp('26/09/02 15:03:20.969000000','RR/MM/DD HH24:MI:SSXFF'),'2','농가 인근 들개 진입 통제 및 상황 종료','/resources/images/dog.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_01');
Insert into SSA.DANGER_LOG (DANLOG_ID,DANGER_TYPE,DANGER_TIME,DACTION_STATUS,DACTION_REASON,DSNAPSHOT_PATH,DANGER_DATE,DRONE_ID) values (4,3,to_timestamp('26/09/02 16:03:20.972000000','RR/MM/DD HH24:MI:SSXFF'),'0','열화상 카메라 산불 징후 연기 포착 완료','/resources/images/smoke.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_03');
Insert into SSA.DANGER_LOG (DANLOG_ID,DANGER_TYPE,DANGER_TIME,DACTION_STATUS,DACTION_REASON,DSNAPSHOT_PATH,DANGER_DATE,DRONE_ID) values (5,2,to_timestamp('26/09/02 17:03:20.975000000','RR/MM/DD HH24:MI:SSXFF'),'0','C3 구역 고라니 2마리 울타리 훼손 포착','/resources/images/deer2.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_02');
Insert into SSA.DANGER_LOG (DANLOG_ID,DANGER_TYPE,DANGER_TIME,DACTION_STATUS,DACTION_REASON,DSNAPSHOT_PATH,DANGER_DATE,DRONE_ID) values (6,1,to_timestamp('26/09/02 17:33:20.978000000','RR/MM/DD HH24:MI:SSXFF'),'1','외곽 초소 부근 멧돼지 출몰 대피 상황 전파','/resources/images/boar3.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_01');
REM INSERTING into SSA.DETECTION_LOG
SET DEFINE OFF;
Insert into SSA.DETECTION_LOG (DLOG_ID,DETECT_TIME,ANIMAL_TYPE,SNAPSHOT_PATH,DETECTION_DATE,DRONE_ID,ACTION_STATUS,ACTION_REASON,DETECT_COUNT) values (1,to_timestamp('26/09/02 13:08:29.550000000','RR/MM/DD HH24:MI:SSXFF'),'개','/resources/images/boar.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_01','0','드론 야간 순찰 중 멧돼지 추정 객체 무리 식별',3);
Insert into SSA.DETECTION_LOG (DLOG_ID,DETECT_TIME,ANIMAL_TYPE,SNAPSHOT_PATH,DETECTION_DATE,DRONE_ID,ACTION_STATUS,ACTION_REASON,DETECT_COUNT) values (2,to_timestamp('26/09/02 14:08:29.553000000','RR/MM/DD HH24:MI:SSXFF'),'개','/resources/images/deer.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_02','1','산림 경계 구역 고라니 출몰로 현장 순찰 대기',1);
Insert into SSA.DETECTION_LOG (DLOG_ID,DETECT_TIME,ANIMAL_TYPE,SNAPSHOT_PATH,DETECTION_DATE,DRONE_ID,ACTION_STATUS,ACTION_REASON,DETECT_COUNT) values (3,to_timestamp('26/09/02 15:08:29.556000000','RR/MM/DD HH24:MI:SSXFF'),'고양이','/resources/images/dog.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_01','2','농가 인근 들개 진입 통제 및 상황 종료',2);
Insert into SSA.DETECTION_LOG (DLOG_ID,DETECT_TIME,ANIMAL_TYPE,SNAPSHOT_PATH,DETECTION_DATE,DRONE_ID,ACTION_STATUS,ACTION_REASON,DETECT_COUNT) values (4,to_timestamp('26/09/02 16:08:29.558000000','RR/MM/DD HH24:MI:SSXFF'),'고양이','/resources/images/smoke.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_03','0','열화상 카메라 산불 징후 연기 포착 완료',1);
Insert into SSA.DETECTION_LOG (DLOG_ID,DETECT_TIME,ANIMAL_TYPE,SNAPSHOT_PATH,DETECTION_DATE,DRONE_ID,ACTION_STATUS,ACTION_REASON,DETECT_COUNT) values (5,to_timestamp('26/09/02 17:08:29.562000000','RR/MM/DD HH24:MI:SSXFF'),'개','/resources/images/deer2.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_02','0','C3 구역 고라니 2마리 울타리 훼손 포착',2);
Insert into SSA.DETECTION_LOG (DLOG_ID,DETECT_TIME,ANIMAL_TYPE,SNAPSHOT_PATH,DETECTION_DATE,DRONE_ID,ACTION_STATUS,ACTION_REASON,DETECT_COUNT) values (6,to_timestamp('26/09/02 17:38:29.564000000','RR/MM/DD HH24:MI:SSXFF'),'고양이','/resources/images/boar3.jpg',to_date('26/09/02','RR/MM/DD'),'DRONE_01','1','외곽 초소 부근 멧돼지 출몰 대피 상황 전파',1);
REM INSERTING into SSA.DRONE
SET DEFINE OFF;
Insert into SSA.DRONE (DRONE_ID,MEMBER_ID) values ('DRONE_01','admin');
Insert into SSA.DRONE (DRONE_ID,MEMBER_ID) values ('DRONE_02','user01');
Insert into SSA.DRONE (DRONE_ID,MEMBER_ID) values ('DRONE_03','user02');
REM INSERTING into SSA.FLIGHT_HISTORY
SET DEFINE OFF;
Insert into SSA.FLIGHT_HISTORY (FLIGHT_ID,START_TIME,END_TIME,FLIGHT_DURATION,BATTERY_CONSUMPTION,FLIGHT_DATE,DRONE_ID) values (1,to_date('26/08/31','RR/MM/DD'),to_date('26/08/31','RR/MM/DD'),1.5,42.3,to_date('26/08/31','RR/MM/DD'),'DRONE_01');
Insert into SSA.FLIGHT_HISTORY (FLIGHT_ID,START_TIME,END_TIME,FLIGHT_DURATION,BATTERY_CONSUMPTION,FLIGHT_DATE,DRONE_ID) values (2,to_date('26/09/01','RR/MM/DD'),to_date('26/09/01','RR/MM/DD'),2.15,68.8,to_date('26/09/01','RR/MM/DD'),'DRONE_02');
Insert into SSA.FLIGHT_HISTORY (FLIGHT_ID,START_TIME,END_TIME,FLIGHT_DURATION,BATTERY_CONSUMPTION,FLIGHT_DATE,DRONE_ID) values (3,to_date('26/09/01','RR/MM/DD'),to_date('26/09/01','RR/MM/DD'),0.75,25.1,to_date('26/09/01','RR/MM/DD'),'DRONE_03');
Insert into SSA.FLIGHT_HISTORY (FLIGHT_ID,START_TIME,END_TIME,FLIGHT_DURATION,BATTERY_CONSUMPTION,FLIGHT_DATE,DRONE_ID) values (4,to_date('26/09/02','RR/MM/DD'),to_date('26/09/02','RR/MM/DD'),2,55,to_date('26/09/02','RR/MM/DD'),'DRONE_01');
Insert into SSA.FLIGHT_HISTORY (FLIGHT_ID,START_TIME,END_TIME,FLIGHT_DURATION,BATTERY_CONSUMPTION,FLIGHT_DATE,DRONE_ID) values (5,to_date('26/09/02','RR/MM/DD'),to_date('26/09/02','RR/MM/DD'),1.85,49.2,to_date('26/09/02','RR/MM/DD'),'DRONE_02');
Insert into SSA.FLIGHT_HISTORY (FLIGHT_ID,START_TIME,END_TIME,FLIGHT_DURATION,BATTERY_CONSUMPTION,FLIGHT_DATE,DRONE_ID) values (6,to_date('26/09/02','RR/MM/DD'),to_date('26/09/02','RR/MM/DD'),1.1,31.4,to_date('26/09/02','RR/MM/DD'),'DRONE_03');
REM INSERTING into SSA.HO_LOCK
SET DEFINE OFF;
REM INSERTING into SSA.HO_NOTE
SET DEFINE OFF;
REM INSERTING into SSA.MEMBER
SET DEFINE OFF;
Insert into SSA.MEMBER (MEMBER_ID,NAME,DEPARTMENT,PASSWORD,STATUS,FAIL_COUNT,PWD_CHG_DATE,LAST_LONG_DATE,REG_DATE,PHONE,EMAIL,PICTURE) values ('user','장지웅','관제원','$2a$10$nvrUyASnsFrEgvVdswTaRuqjAXMRY4IOcfosbmXS9mt2nOw0LJZX2','1',0,to_date('26/09/01','RR/MM/DD'),to_date('26/09/01','RR/MM/DD'),to_date('26/09/01','RR/MM/DD'),'010-1234-1234','bb@bb.com','noImage.jpg');
Insert into SSA.MEMBER (MEMBER_ID,NAME,DEPARTMENT,PASSWORD,STATUS,FAIL_COUNT,PWD_CHG_DATE,LAST_LONG_DATE,REG_DATE,PHONE,EMAIL,PICTURE) values ('user01','관제원01','운영팀','1234','0',0,to_date('26/09/02','RR/MM/DD'),null,to_date('26/09/02','RR/MM/DD'),null,'user01@ssa.com','noImage.jpg');
Insert into SSA.MEMBER (MEMBER_ID,NAME,DEPARTMENT,PASSWORD,STATUS,FAIL_COUNT,PWD_CHG_DATE,LAST_LONG_DATE,REG_DATE,PHONE,EMAIL,PICTURE) values ('user02','관제원02','운영팀','1234','0',0,to_date('26/09/02','RR/MM/DD'),null,to_date('26/09/02','RR/MM/DD'),null,'user02@ssa.com','noImage.jpg');
Insert into SSA.MEMBER (MEMBER_ID,NAME,DEPARTMENT,PASSWORD,STATUS,FAIL_COUNT,PWD_CHG_DATE,LAST_LONG_DATE,REG_DATE,PHONE,EMAIL,PICTURE) values ('admin','강동현','관리자','$2a$10$FWTw75iUzcqpoJA0lfjo..PCDqv4RxDzJKhXVV2B8dLJioWvAzVvi','0',0,to_date('26/09/01','RR/MM/DD'),to_date('26/09/03','RR/MM/DD'),to_date('26/09/01','RR/MM/DD'),'010-9304-8747','dhkang8816@naver.com','noImage.jpg');
REM INSERTING into SSA.MEMBER_LOG
SET DEFINE OFF;
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (10,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (11,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (12,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (13,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (14,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (15,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (8,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (9,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (16,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (17,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (18,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (19,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (20,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (21,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (22,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (23,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (24,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (25,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (26,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (27,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (28,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (29,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (30,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (31,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (32,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (33,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (34,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (35,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (36,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (37,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (38,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (39,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (40,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (41,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (42,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (43,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (44,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (45,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (46,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (47,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (48,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (49,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (50,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'user');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (51,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'user');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (52,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'user');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (53,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'user');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (54,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'user');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (55,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'user');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (56,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (57,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (58,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (59,'0:0:0:0:0:0:0:1','FAIL',to_date('26/09/01','RR/MM/DD'),'user');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (60,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'user');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (61,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (62,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (63,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (64,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (65,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/01','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (66,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (67,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (68,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (69,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (70,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (71,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (72,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (73,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (74,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (75,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (76,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (77,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (78,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (79,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (80,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (81,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (82,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (83,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (84,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (85,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (86,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (87,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (88,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (89,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (90,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (91,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (92,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (93,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (94,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (95,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (96,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (97,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (98,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (99,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/02','RR/MM/DD'),'admin');
Insert into SSA.MEMBER_LOG (LOG_ID,LOGIN_IP,LOGIN_STATUS,LOGIN_DATE,MEMBER_ID) values (100,'0:0:0:0:0:0:0:1','SUCCESS',to_date('26/09/03','RR/MM/DD'),'admin');
REM INSERTING into SSA.MEMBER_ROLE
SET DEFINE OFF;
Insert into SSA.MEMBER_ROLE (ROLE_ID,ROLE_CODE,MEMBER_ID) values (3,'ROLE_ADMIN','admin');
Insert into SSA.MEMBER_ROLE (ROLE_ID,ROLE_CODE,MEMBER_ID) values (4,'ROLE_GUEST','user');
Insert into SSA.MEMBER_ROLE (ROLE_ID,ROLE_CODE,MEMBER_ID) values (1,'ROLE_GUEST','admin');
Insert into SSA.MEMBER_ROLE (ROLE_ID,ROLE_CODE,MEMBER_ID) values (2,'ROLE_USER','admin');
REM INSERTING into SSA.PATROL_REPORT
SET DEFINE OFF;
REM INSERTING into SSA.PDF_CACHE
SET DEFINE OFF;
REM INSERTING into SSA.WORKFLOW
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ALERT_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_ALERT_LOG" ON "SSA"."ALERT_LOG" ("ALERT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ANIMAL_COUNTER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_ANIMAL_COUNTER" ON "SSA"."ANIMAL_COUNTER" ("COUNTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ANIMAL_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_ANIMAL_DETAIL" ON "SSA"."ANIMAL_DETAIL" ("ANIMAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_COMMON_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_COMMON_CODE" ON "SSA"."COMMON_CODE" ("GRP_CODE", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DANGER_DETAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_DANGER_DETAIL" ON "SSA"."DANGER_DETAIL" ("DANGER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DANGER_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_DANGER_LOG" ON "SSA"."DANGER_LOG" ("DANLOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DETECTION_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_DETECTION_LOG" ON "SSA"."DETECTION_LOG" ("DLOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_DRONE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_DRONE" ON "SSA"."DRONE" ("DRONE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_FLIGHT_HISTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_FLIGHT_HISTORY" ON "SSA"."FLIGHT_HISTORY" ("FLIGHT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_HO_LOCK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_HO_LOCK" ON "SSA"."HO_LOCK" ("LOCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_HO_NOTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_HO_NOTE" ON "SSA"."HO_NOTE" ("HANDOVER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_MEMBER" ON "SSA"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER_LOG
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_MEMBER_LOG" ON "SSA"."MEMBER_LOG" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER_ROLE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_MEMBER_ROLE" ON "SSA"."MEMBER_ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PATROL_REPORT
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_PATROL_REPORT" ON "SSA"."PATROL_REPORT" ("REPORT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PDF_CACHE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_PDF_CACHE" ON "SSA"."PDF_CACHE" ("PDF_CACHE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_WORKFLOW
--------------------------------------------------------

  CREATE UNIQUE INDEX "SSA"."PK_WORKFLOW" ON "SSA"."WORKFLOW" ("APPROVAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ALERT_LOG
--------------------------------------------------------

  ALTER TABLE "SSA"."ALERT_LOG" ADD CONSTRAINT "PK_ALERT_LOG" PRIMARY KEY ("ALERT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."ALERT_LOG" MODIFY ("ALERT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ALERT_LOG" MODIFY ("FIRST_SEND_TIME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ALERT_LOG" MODIFY ("SEND_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ALERT_LOG" MODIFY ("SEND_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ALERT_LOG" MODIFY ("ALERT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANIMAL_COUNTER
--------------------------------------------------------

  ALTER TABLE "SSA"."ANIMAL_COUNTER" ADD CONSTRAINT "PK_ANIMAL_COUNTER" PRIMARY KEY ("COUNTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."ANIMAL_COUNTER" MODIFY ("LAST_UPDATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ANIMAL_COUNTER" MODIFY ("CURRENT_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ANIMAL_COUNTER" MODIFY ("COUNTER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANIMAL_DETAIL
--------------------------------------------------------

  ALTER TABLE "SSA"."ANIMAL_DETAIL" MODIFY ("ANIMAL_BREED" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ANIMAL_DETAIL" MODIFY ("ANIMAL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ANIMAL_DETAIL" MODIFY ("ANIMAL_ID" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ANIMAL_DETAIL" ADD CONSTRAINT "PK_ANIMAL_DETAIL" PRIMARY KEY ("ANIMAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."ANIMAL_DETAIL" MODIFY ("ANIMAL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ANIMAL_DETAIL" MODIFY ("ENTRANCE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."ANIMAL_DETAIL" MODIFY ("ANIMAL_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMON_CODE
--------------------------------------------------------

  ALTER TABLE "SSA"."COMMON_CODE" ADD CONSTRAINT "PK_COMMON_CODE" PRIMARY KEY ("GRP_CODE", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."COMMON_CODE" MODIFY ("CODE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."COMMON_CODE" MODIFY ("USE_YN" NOT NULL ENABLE);
  ALTER TABLE "SSA"."COMMON_CODE" MODIFY ("SORT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "SSA"."COMMON_CODE" MODIFY ("CODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."COMMON_CODE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."COMMON_CODE" MODIFY ("GRP_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DANGER_DETAIL
--------------------------------------------------------

  ALTER TABLE "SSA"."DANGER_DETAIL" ADD CONSTRAINT "PK_DANGER_DETAIL" PRIMARY KEY ("DANGER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."DANGER_DETAIL" MODIFY ("DANGER_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DANGER_DETAIL" MODIFY ("DANGER_NAME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DANGER_DETAIL" MODIFY ("DANGER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DANGER_LOG
--------------------------------------------------------

  ALTER TABLE "SSA"."DANGER_LOG" ADD CONSTRAINT "PK_DANGER_LOG" PRIMARY KEY ("DANLOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."DANGER_LOG" MODIFY ("DANGER_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DANGER_LOG" MODIFY ("DSNAPSHOT_PATH" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DANGER_LOG" MODIFY ("DACTION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DANGER_LOG" MODIFY ("DANGER_TIME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DANGER_LOG" MODIFY ("DANGER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DANGER_LOG" MODIFY ("DANLOG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETECTION_LOG
--------------------------------------------------------

  ALTER TABLE "SSA"."DETECTION_LOG" ADD CONSTRAINT "PK_DETECTION_LOG" PRIMARY KEY ("DLOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."DETECTION_LOG" MODIFY ("DETECT_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DETECTION_LOG" MODIFY ("ACTION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DETECTION_LOG" MODIFY ("DETECTION_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DETECTION_LOG" MODIFY ("SNAPSHOT_PATH" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DETECTION_LOG" MODIFY ("ANIMAL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DETECTION_LOG" MODIFY ("DETECT_TIME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."DETECTION_LOG" MODIFY ("DLOG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DRONE
--------------------------------------------------------

  ALTER TABLE "SSA"."DRONE" ADD CONSTRAINT "PK_DRONE" PRIMARY KEY ("DRONE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."DRONE" MODIFY ("DRONE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FLIGHT_HISTORY
--------------------------------------------------------

  ALTER TABLE "SSA"."FLIGHT_HISTORY" ADD CONSTRAINT "PK_FLIGHT_HISTORY" PRIMARY KEY ("FLIGHT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."FLIGHT_HISTORY" MODIFY ("FLIGHT_DURATION" NOT NULL ENABLE);
  ALTER TABLE "SSA"."FLIGHT_HISTORY" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."FLIGHT_HISTORY" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."FLIGHT_HISTORY" MODIFY ("FLIGHT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HO_LOCK
--------------------------------------------------------

  ALTER TABLE "SSA"."HO_LOCK" ADD CONSTRAINT "PK_HO_LOCK" PRIMARY KEY ("LOCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."HO_LOCK" MODIFY ("HANDOVER_ID" NOT NULL ENABLE);
  ALTER TABLE "SSA"."HO_LOCK" MODIFY ("LOCK_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SSA"."HO_LOCK" MODIFY ("LOCK_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."HO_LOCK" MODIFY ("LOCK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HO_NOTE
--------------------------------------------------------

  ALTER TABLE "SSA"."HO_NOTE" ADD CONSTRAINT "PK_HO_NOTE" PRIMARY KEY ("HANDOVER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."HO_NOTE" MODIFY ("HI_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SSA"."HO_NOTE" MODIFY ("HO_MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SSA"."HO_NOTE" MODIFY ("HANDOUT_SIGN" NOT NULL ENABLE);
  ALTER TABLE "SSA"."HO_NOTE" MODIFY ("HANDOVER_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."HO_NOTE" MODIFY ("HANDOVER_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."HO_NOTE" MODIFY ("HANDOVER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SSA"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."MEMBER" MODIFY ("PICTURE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("PWD_CHG_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("FAIL_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("DEPARTMENT" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_LOG
--------------------------------------------------------

  ALTER TABLE "SSA"."MEMBER_LOG" ADD CONSTRAINT "PK_MEMBER_LOG" PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."MEMBER_LOG" MODIFY ("LOGIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER_LOG" MODIFY ("LOGIN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER_LOG" MODIFY ("LOGIN_IP" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER_LOG" MODIFY ("LOG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_ROLE
--------------------------------------------------------

  ALTER TABLE "SSA"."MEMBER_ROLE" ADD CONSTRAINT "PK_MEMBER_ROLE" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."MEMBER_ROLE" MODIFY ("ROLE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."MEMBER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATROL_REPORT
--------------------------------------------------------

  ALTER TABLE "SSA"."PATROL_REPORT" ADD CONSTRAINT "PK_PATROL_REPORT" PRIMARY KEY ("REPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."PATROL_REPORT" MODIFY ("PATROL_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."PATROL_REPORT" MODIFY ("CONFIRM_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."PATROL_REPORT" MODIFY ("COMPLETION_RATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."PATROL_REPORT" MODIFY ("TOTAL_DETECT_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SSA"."PATROL_REPORT" MODIFY ("TOTAL_FLIGHT_TIME" NOT NULL ENABLE);
  ALTER TABLE "SSA"."PATROL_REPORT" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."PATROL_REPORT" MODIFY ("REPORT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PDF_CACHE
--------------------------------------------------------

  ALTER TABLE "SSA"."PDF_CACHE" ADD CONSTRAINT "PK_PDF_CACHE" PRIMARY KEY ("PDF_CACHE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."PDF_CACHE" MODIFY ("PDF_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."PDF_CACHE" MODIFY ("GENERATION_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."PDF_CACHE" MODIFY ("PDF_CACHE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table WORKFLOW
--------------------------------------------------------

  ALTER TABLE "SSA"."WORKFLOW" ADD CONSTRAINT "PK_WORKFLOW" PRIMARY KEY ("APPROVAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SSA"."WORKFLOW" MODIFY ("APPROVER_ID" NOT NULL ENABLE);
  ALTER TABLE "SSA"."WORKFLOW" MODIFY ("DRAFTER_ID" NOT NULL ENABLE);
  ALTER TABLE "SSA"."WORKFLOW" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "SSA"."WORKFLOW" MODIFY ("ADMIN_SIGN" NOT NULL ENABLE);
  ALTER TABLE "SSA"."WORKFLOW" MODIFY ("APP_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SSA"."WORKFLOW" MODIFY ("APPROVAL_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ALERT_LOG
--------------------------------------------------------

  ALTER TABLE "SSA"."ALERT_LOG" ADD CONSTRAINT "FK_DANGER_LOG_TO_ALERT_LOG" FOREIGN KEY ("DANLOG_ID")
	  REFERENCES "SSA"."DANGER_LOG" ("DANLOG_ID") ENABLE;
  ALTER TABLE "SSA"."ALERT_LOG" ADD CONSTRAINT "FK_DETECTION_LOG_TO_ALERT_LOG" FOREIGN KEY ("DLOG_ID")
	  REFERENCES "SSA"."DETECTION_LOG" ("DLOG_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DANGER_LOG
--------------------------------------------------------

  ALTER TABLE "SSA"."DANGER_LOG" ADD CONSTRAINT "FK_DRONE_TO_DANGER_LOG" FOREIGN KEY ("DRONE_ID")
	  REFERENCES "SSA"."DRONE" ("DRONE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETECTION_LOG
--------------------------------------------------------

  ALTER TABLE "SSA"."DETECTION_LOG" ADD CONSTRAINT "FK_DRONE_TO_DETECTION_LOG" FOREIGN KEY ("DRONE_ID")
	  REFERENCES "SSA"."DRONE" ("DRONE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DRONE
--------------------------------------------------------

  ALTER TABLE "SSA"."DRONE" ADD CONSTRAINT "FK_MEMBER_TO_DRONE" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SSA"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FLIGHT_HISTORY
--------------------------------------------------------

  ALTER TABLE "SSA"."FLIGHT_HISTORY" ADD CONSTRAINT "FK_DRONE_TO_FLIGHT_HISTORY" FOREIGN KEY ("DRONE_ID")
	  REFERENCES "SSA"."DRONE" ("DRONE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HO_LOCK
--------------------------------------------------------

  ALTER TABLE "SSA"."HO_LOCK" ADD CONSTRAINT "FK_HO_NOTE_TO_HO_LOCK" FOREIGN KEY ("HANDOVER_ID")
	  REFERENCES "SSA"."HO_NOTE" ("HANDOVER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HO_NOTE
--------------------------------------------------------

  ALTER TABLE "SSA"."HO_NOTE" ADD CONSTRAINT "FK_MEMBER_TO_HO_NOTE" FOREIGN KEY ("HO_MEMBER_ID")
	  REFERENCES "SSA"."MEMBER" ("MEMBER_ID") ENABLE;
  ALTER TABLE "SSA"."HO_NOTE" ADD CONSTRAINT "FK_MEMBER_TO_HO_NOTE2" FOREIGN KEY ("HI_MEMBER_ID")
	  REFERENCES "SSA"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_LOG
--------------------------------------------------------

  ALTER TABLE "SSA"."MEMBER_LOG" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_LOG" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SSA"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_ROLE
--------------------------------------------------------

  ALTER TABLE "SSA"."MEMBER_ROLE" ADD CONSTRAINT "FK_MEMBER_TO_MEMBER_ROLE" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SSA"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATROL_REPORT
--------------------------------------------------------

  ALTER TABLE "SSA"."PATROL_REPORT" ADD CONSTRAINT "FK_MEMBER_TO_PATROL_REPORT" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SSA"."MEMBER" ("MEMBER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PDF_CACHE
--------------------------------------------------------

  ALTER TABLE "SSA"."PDF_CACHE" ADD CONSTRAINT "FK_PATROL_REPORT_TO_PDF_CACHE" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "SSA"."PATROL_REPORT" ("REPORT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WORKFLOW
--------------------------------------------------------

  ALTER TABLE "SSA"."WORKFLOW" ADD CONSTRAINT "FK_MEMBER_TO_WORKFLOW" FOREIGN KEY ("DRAFTER_ID")
	  REFERENCES "SSA"."MEMBER" ("MEMBER_ID") ENABLE;
  ALTER TABLE "SSA"."WORKFLOW" ADD CONSTRAINT "FK_MEMBER_TO_WORKFLOW2" FOREIGN KEY ("APPROVER_ID")
	  REFERENCES "SSA"."MEMBER" ("MEMBER_ID") ENABLE;
  ALTER TABLE "SSA"."WORKFLOW" ADD CONSTRAINT "FK_PATROL_REPORT_TO_WORKFLOW" FOREIGN KEY ("REPORT_ID")
	  REFERENCES "SSA"."PATROL_REPORT" ("REPORT_ID") ENABLE;
